### ISSUE TITLE
CSS is broken when running in Gitpod

### ISSUE THREAD

**Issue by gatezh** [zeon-studio/hugoplate#126]
### What is your Hugo Extended Version

v0.125.4

### What is your Go Version

v1.22.2

### What is your Node.js Version

v20.12.2

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Expecting to see a website with CSS styling in the preview window of Gitpod workspace

### Steps to Reproduce

1. Create `.gitpod.yml` configuration file in the root folder with the following content:
     ```yml
    tasks:
      - name: Dev server
        before: brew install hugo
        init: npm install
        command: npm run dev
    
    ports:
      - port: 1313
        onOpen: open-preview
    ```
2. Commit changes
3. Open the repo in Gitpod by prefixing the URL with: `gitpod.io/#`. For example, `https://gitpod.io/#https://github.com/gatezh/hugoplate-fork`
4. Project preview has no styling

### Code Reproduction URL

https://github.com/gatezh/hugoplate-fork

### Additional Information

It is more like a feature request rather then a bug. I would really appreciate if you could to help with this issue
