### ISSUE TITLE
Buttons in homepage not showing

### ISSUE THREAD

**Issue by rickdkk** [zeon-studio/hugoplate#23]
Hi,

I couldn't get the buttons on the features sections on the homepage to work. In the example site one of the buttons is also enabled and not showing, so I think this is not just an issue on my side.

```
button:
  enable: true
  label: "Get Started Now"
  link: "https://github.com/zeon-studio/hugoplate"
```

Is this a bug or am I overlooking a global setting somewhere?

Best,
rickdkk
