### ISSUE TITLE
Syntax Highlighter color issue with light and dark mode

### ISSUE THREAD

**Issue by happytodev** [zeon-studio/hugoplate#35]
Hello,

Is there a way to easily customize syntax highlighter color for light and dark mode.

Currently, in light mode some parts of code are unreadable. See the screenshots below :

<img width="862" alt="image" src="https://github.com/zeon-studio/hugoplate/assets/425998/7efb678e-f986-4135-ad04-5afdec9d836e">

<img width="876" alt="image" src="https://github.com/zeon-studio/hugoplate/assets/425998/d511b3e0-dab8-41a0-834e-41cf4a45c7c0">

You have the same problems on [Elements demo page](https://hugoplate.netlify.app/elements/) : 

<img width="868" alt="image" src="https://github.com/zeon-studio/hugoplate/assets/425998/a05be74c-d32a-4c51-83bf-5335a5146459">

Thanks for your help.

**Comment by tfsomrat** [comment]
hey @happytodev, thanks for noticing. this issue has been fixed, please update the theme.

**Comment by happytodev** [comment]
> hey @happytodev, thanks for noticing. this issue has been fixed, please update the theme.

Hey @tfsomrat thank you. I just see your answer now ;-)

What is the best way for updating the theme ?
Is there a cache to empty ?

Thank you for your advices

**Comment by happytodev** [comment]
I tried npm update + npm run update-modules but I always have the same problem.

**Comment by tfsomrat** [comment]
hey @happytodev, same problem means which problem?

**Comment by happytodev** [comment]
![image](https://github.com/zeon-studio/hugoplate/assets/425998/3082c991-8e2b-4362-bf62-4f240aefffa7)

Hello @tfsomrat,  the same code syntax that is unreadeable 👆

**Comment by tfsomrat** [comment]
which version of the theme you are using? check package.json for version.

**Comment by happytodev** [comment]
> which version of the theme you are using? check package.json for version.

  "name": "hugoplate",
  "description": "hugo tailwindcss boilerplate",
  "version": "1.7.1",

**Comment by tfsomrat** [comment]
You are using the old version, the current version is 1.7.7 https://github.com/zeon-studio/hugoplate/blob/39e487943d6dfbdd4299b7bf1d0790ef9103f71d/package.json#L4

**Comment by happytodev** [comment]
> You are using the old version, the current version is 1.7.7
> 
> https://github.com/zeon-studio/hugoplate/blob/39e487943d6dfbdd4299b7bf1d0790ef9103f71d/package.json#L4

I changed it and run

`npm update`

I still stuck with the same error.

**Comment by tfsomrat** [comment]
please follow this guide to update your theme https://docs.gethugothemes.com/guide/#theme-update

**Comment by happytodev** [comment]
> please follow this guide to update your theme https://docs.gethugothemes.com/guide/#theme-update

Hello,

Thanks it's ok now.

I updated files manually.

In the future, do you plan to simplify update themes method ?

**Comment by happytodev** [comment]
> please follow this guide to update your theme https://docs.gethugothemes.com/guide/#theme-update

One more question please. In local with `npm run dev` it works but when I deploy via Github Actions my production site still with the same error.

Do you any advice for me please ?

I use this : 

```yml
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Hugo
        run: |
          curl -LO "https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz"
          tar -xvf hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          rm hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz
          hugo version

      - name: Install Go
        run: |
          curl -LO "https://dl.google.com/go/go${{ env.GO_VERSION }}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          rm go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          go version

      - name: Setup Project
        run: npm run project-setup

      - name: Install npm dependencies
        run: npm install

      - name: npm update
        run: npm update 
        
      - name: update modules
        run: npm run update-modules
        
      - name: npm run build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
```

Thank you for your help
